name: Deploy to GitHub Pages
on: [push]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          npm i
          npm run build

      - name: Deploy 🚀
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "Articulate Bot"
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/yzAlvin/articulate.git
          npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}