export const brands: string[] = [
    "Apple",
    "Google",
    "Microsoft",
    "Amazon",
    "Facebook",
    "Coca - Cola",
    "Disney",
    "Samsung",
    "Louis Vuitton",
    "McDonald's",
    "Toyota",
    "Intel",
    "NIKE",
    "AT & T",
    "Cisco",
    "Oracle",
    "Verizon",
    "Visa",
    "Walmart",
    "GE",
    "Budweiser",
    "SAP",
    "Mercedes - Benz",
    "IBM",
    "Marlboro",
    "Netflix",
    "BMW",
    "American Express",
    "Honda",
    "L'Oréal",
    "Gucci",
    "Hermès",
    "Nescafe",
    "Home Depot",
    "Accenture",
    "Pepsi",
    "Starbucks",
    "Mastercard",
    "Frito - Lay",
    "IKEA",
    "Zara",
    "Gillette",
    "HSBC",
    "Audi",
    "J.P.Morgan",
    "Deloitte",
    "Sony",
    "UPS",
    "Bank of America",
    "Chase",
];