export const people: string[] = [
    "Sean Connery",
    "Captain Kirk",
    "The Wizard of Oz",
    "Denise Welch",
    "Keirar Knightley",
    "J R R Tolkien",
    "Russel Crowe",
    "Cameron Diaz",
    "Jude Law",
    "Dennis the Menace",
    "Rasputin",
    "Sir Edmund Hillary",
    "Louis Spence",
    "Santa Claus",
    "Napoleon Bonaparte",
    "Ernest Hemingway",
    "The Phanom",
];